apiVersion: v1
kind: Service
metadata:
  name: project-one-service-1
spec:
  selector:
    app: project-one  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8001 
  type: LoadBalancer
